### ISSUE TITLE
Milestone1-StoryPoint06: Visualisation des trajectoires d'un appareil GPS sur ThreeJS

### ISSUE THREAD

**Issue by LinaSaba** [zumbalove974/oxfam-trailwalker#10]
- Récupération de 20 lignes de coordonnées d'un appareil GPS,
- Intégration sur QGIS 
- Convertir les points en une ligne
- Visualisation de la trajectoire sur une page ThreeJS

**Comment by VenziaTurmoil** [comment]
The deed was done by my bro Omran
