### ISSUE TITLE
Sprint05UserStory7 : test unitaires front

### ISSUE THREAD

**Issue by hibaa-ai** [zumbalove974/oxfam-trailwalker#102]
tests unitaires front

**Comment by LinaSaba** [comment]
- Chacun se charge de tester un composant/ page : 
- 4 pages : Home, About, Application, Team (pas encore créée, à tester prochain sprint ou jeudi)
- 2 composants : MenuBar, VisuMur
mettre qui veut se charger de quoi entre () pls

**Comment by LinaSaba** [comment]
nsm
