### ISSUE TITLE
Milestone2>3>4: ** Visu-épaisseur densité de coureurs

### ISSUE THREAD

**Issue by LinaSaba** [zumbalove974/oxfam-trailwalker#16]

**Comment by VenziaTurmoil** [comment]
La visu epaisseur par vitesse est implementee

**Comment by VenziaTurmoil** [comment]
Cest full bug + il vaut mieux attendre la clusterisation des trajectoires

**Comment by VenziaTurmoil** [comment]
Reprise pour le sprint suivant, avec les donnees clusterisees

**Comment by VenziaTurmoil** [comment]
Il manque la densite de coureurs
