### ISSUE TITLE
Reflechir a une organisation saine de nos fichiers de code

### ISSUE THREAD

**Issue by VenziaTurmoil** [zumbalove974/oxfam-trailwalker#27]
En particulier pour l'implementations correcte des differentes visualisations

**Comment by VenziaTurmoil** [comment]
Idee : fichier de config du plugin importe dans les fichiers pour chacune des visu

**Comment by LinaSaba** [comment]
ou les afficher comme des composants ? 
chaque visu est un composant qu'on peut ajouter à la carte avec sa barre explicative de comment rajouter chaque fontionnalité/visu
